# Generated by Django 3.2.3 on 2021-05-19 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programtitle', models.CharField(max_length=250)),
                ('descriptions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('lastname', models.CharField(max_length=125)),
                ('firstname', models.CharField(max_length=125)),
                ('midname', models.CharField(max_length=125, null=True)),
                ('extname', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('homeadd', models.TextField(blank=True, null=True)),
                ('fathername', models.CharField(max_length=250)),
                ('fatheroccu', models.CharField(max_length=125)),
                ('mothername', models.CharField(max_length=250)),
                ('motheroccu', models.CharField(max_length=125)),
                ('phonenumber', models.CharField(max_length=50)),
                ('prevschool', models.CharField(max_length=250)),
                ('acadyear', models.CharField(max_length=25)),
                ('yearlevel', models.CharField(max_length=25)),
                ('courses', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enroll.program')),
            ],
        ),
    ]
