# Generated by Django 3.2.3 on 2021-05-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_alter_student_extname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='extname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='midname',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
