# Generated by Django 3.2.3 on 2021-05-19 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_auto_20210519_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='courses',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='acadyear',
        ),
        migrations.RemoveField(
            model_name='student',
            name='yearlevel',
        ),
        migrations.CreateModel(
            name='Enrolmentrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acadyear', models.CharField(max_length=25)),
                ('yearlevel', models.CharField(max_length=25)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='enroll.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.student')),
            ],
        ),
    ]
